### ISSUE TITLE
plan-to-issues: close the gaps left by the #106 review fixes

### ISSUE THREAD

**Issue by luongnv89** [luongnv89/skills#108]
## Problem

The review fixes merged in #106 (`0cfe0b4`, `688ef83`) were verified by a confirmation pass that
completed *after* the merge. It found three of the eight fixes only partially applied, and three
new defects introduced by the fixes themselves.

## Open defects on `main`

**1. The duplicate-epic window is narrowed, not closed.** SKILL.md Phase 3 creates the epic at step 2
but writes the plan-binding marker at step 4. An interruption in that gap leaves a markerless epic
that step 1 cannot find, so a re-run creates a second epic — the exact bug #107 set out to fix. The
previous title/plan-path heuristic was removed, so there is no fallback.

**2. `gh --title-file` does not exist.** SKILL.md's Prompt Injection Boundary recommends it. `gh issue
edit`/`gh issue create` expose only `-t/--title string`; the sole file-based flag is `-F/--body-file`.
An agent following this guidance emits a command that fails.

**3. The "shell-safe" repair snippet is not shell-safe.** `references/issue-creator-bridge.md` writes
`title="<task-id>: <title>"`, pasting untrusted plan text into a double-quoted assignment — the same
injection surface the surrounding rule forbids. The variable indirection only protects the second line.

**4. Renderer input validation covers 2 of 8 shapes.** `phases[i]` not a dict, `milestone` not a dict,
`depends_on` / `unknown_deps` / `critical_path` / `deferred` not lists all raise an uncaught traceback
(exit 1) instead of the documented exit 2 + hint. Worse, `depends_on: "T1"` exits 0 and renders
fabricated per-character dependencies (`⚠ unknown dep T · ⚠ unknown dep 1`).

**5. `cell()` escapes only inside tables.** A newline in plan text still corrupts non-table output: a
phase title containing one splits the `### P0 — Stab` heading mid-line, and the same breaks the
`- [x] #N — <id> <title>` grammar that sync's child-parsing grep depends on.

**6. Phase 3's completion criteria does not check what it claims.** It states "exactly one
`plan-dashboard` sentinel pair" but the command greps only `plan-to-issues:plan=`.

**7. Bridge Step 1 omits the marker write.** `references/issue-creator-bridge.md` Step 1 is the
operational recipe for epic creation and ends at `gh issue edit <epic> --add-label epic`. An agent
working from the bridge rather than SKILL.md Phase 3 skips the marker entirely and reintroduces
defect 1.

Defects 2, 3 and 6 were introduced by the #106 fixes.

## Acceptance Criteria

- [ ] The epic carries its plan-binding marker from the instant it exists — no interruption window between creation and marker write yields a duplicate epic
- [ ] No `gh` flag is named that `gh` does not implement
- [ ] No documented snippet pastes plan-derived text into a shell literal; plan text reaches shell only via a variable sourced from parsed data
- [ ] Every render-input shape either renders or exits 2 with a hint — no traceback, and no input that exits 0 with fabricated content
- [ ] Plan-derived text is newline-collapsed everywhere it is rendered, not only in table cells
- [ ] Every stated completion criterion is verified by the command given for it
- [ ] The bridge reference cannot be followed to a markerless epic
